= Arquitectura guiadad por tradeoffs y riesgos
**11-05-2024**

*Objetivo*: Entender cómo la arquitectura de software debe estar guiada por los
riesgos y que los intercambios de valor que son inveitables y tienen que ser
considerados, manejados y expresados de forma clara.
*Motivación*: Pensar que existe la solución perfecta es un error que cometemos
muy seguido como desarrolladores de software. Y pensar siempre en positivo lleva
a desastres que queremos evitar.
*Prerrequisitos o pretrabajo*: Tener claros los drivers comunes de la arquitectura:
Atributos arquitectónicos, funciones, restricciones, principios y riesgos.

== Temas

1. Tradeoffs: ¿Qué son? ¿Cómo reconocerlos y documentarlos? ¿Cómo hacer un análisis
de tradeoffs?
2. Riesgos: ¿Qué son? ¿Cómo reconocerlos y documentarlos? ¿Cómo diseñar para mitigarlos?
3. Evitar el resulting: ¿Qué es? ¿Cómo evitarlo?
4. 

== Actividades

1. Que creen su propio análisis de tradeoffs para su sistema.

== Tutores

Rodrigo Rodríguez
Héctor Patricio

== Fuentes

Fuentes de información que se utilizarán para preparar la clase.

== Recursos

== Notas extra

Cualquier aclaración o nota a tomar en cuenta para que la clse se lleve
de le mejor forma posible.

