= Estilos y patrones de arquitectura
18-Mayo-2024, 11AM GMT-6 (CDMX)

*Objetivo*: Introducción a los estilos de arquitectura y empezar a analizar
su relación con los atributos arquitectónicos.
*Motivación*: Construir arquitecturas efectivas depende de entender los
elementos que le dan forma. Los estilos y patrones de arquitectura te
dan varias cosas:
1. Un conjunto de herramientas para resolver problemas comunes, sin tener
que descubrirlo todo de nuevo.
2. Un lenguaje común para discutir y documentar decisiones.

*Prerrequisitos o pretrabajo*: Estudiar los el módulo 3 del curso grabado
de arquitectura.

== Temas

Lista de temas o subtemas a cubrir lo más detalladamentes posible.


== Actividades

Plan de actividades de la clase

== Tutores

Nombre y semblanza de los tutores.

== Fuentes

Fuentes de información que se utilizarán para preparar la clase.

== Recursos

Documentos o materiales que se utilizarán durante la clase.

== Notas extra

Cualquier aclaración o nota a tomar en cuenta para que la clse se lleve
de le mejor forma posible.
