== Caso Práctico: Sistema de Pagos Offline

*EventosCadaVezMásCaros* quiere implementar un sistema de pagos offline
para sus eventos musicales y festivales. Normalmente, por la cantidad de personas
que asiste, los problemas de conectividad son comunes y las personas tienen poco o nulo
acceso a internet. Los lugares en los que se realiza el evento no tienen WiFi confiable y
las redes celulares funcionan intermitentemente.

== Descripción detallada del problema

*EventosCadaVezMásCaros* hace eventos musicales en diferentes partes del mundo. Gran 
parte de las ganancias de estos eventos vienen de la venta a precios premium de 
alimentos y bebidas en el lugar. Sin embargo, el manejo de efectivo es riesgoso y poco
conveniente ("No tengo vuelto", "Ya tiré mi efectivo", "Tengo que contar lo de la venta del día" etc.).
Es por eso que la empresa ha usado soluciones de pago sin efectivo en sus eventos, en los que 
los asitentes tienen que adquirir una pulsera con un chip NFC que les permite hacer pagos en los
puntos de venta y con los vendedores ambulantes en los eventos. Los vendedores tienen cada uno un
dispositivo que puede leer los NFC y autorizar la venta.

Sin embargo, al pertenecer a una empresa externa, el sistema es una gran fuga de 
ganancias (las comisiones son muy altas) y un problema logístico del que los
clientes siempre se han quejado, porque tienen que obtener la pulsea antes, sin pulsera
no pueden comprar, tienen que "recargarla" y finamlmente hacer devoluciones es un problema para todos.

Además, se nota una merma de inventario del entre el 15 y 20% en cada evento, nos hemos dado
cuenta que los vendedores a veces venden el inventario en efectivo sin reportalo y que intentan
incluso dañar los POVs para perder la información reportada.

Necesitamos un sistema que nos ayude a resolver los puntos logísticos antes mencionados así como 
disminuir la merma de inventario al máximo posible.

Algunas ideas que tenemos sobr lo que necesitamos:

- Procesar transacciones offline y sincronizarlas cuando haya conexión disponible.
- Este sistema no estará en uso la mayoría del tiempo, pero cunado se usa se procesarán un aproximado de 
500,000 transacciones por día.
- Evitar el abuso del sistema para reducir el robo.

Estamos abiertos al uso de hardware especializado, pero al ser eventos esporádico no podemos
dejarlo instaldo permanentemente.

