= Sistema para la venta de vuelos privados

En este caso práctico nos centraremos en la conexión con sistemas externos
esenciales y en la creación de una aplicación para atender a los cleintes.

== Intro

La areolinea "Aeronaútica Opulenta", quiere crear un sistema de venta de
vuelos privados para sus clientes muy opulentos. La empresa tiene cerca de 300 clientes,
tanto individuales como empresas, pero solución es para clientes personales.

== Descripción

Aeronaútica Opulenta ha operado durante más de 10 años y actualmente
está en un punto crítico porque su rentabilidad es muy baja, aunque sus ventas grandes.
Quiere hacer un sistema para vender vuelos directamente a sus clientes, sin intermediarios.

El sistema debe ser capaz de manejar información sensible de los clientes,
integrarse con los sistemas de pago existentes, considerando que los proveedores
de soluciones de pago son muy cautos con las cantidades que la empresa manja (desde 10k hasta 100k USD por vuelo).

Se venderán tres tipos de vuelos:

- Charters: Vuelos privados solicitados por un cliente.
- Vuelos programados: Vuelos aprovechados por la empresa al tener piernas vacías.
- Vuelos compartidos: Vuelos que se venden a varios clientes.

El sistema de agendado de vuelos es muy complejo y se maneja en un sistemao externo
con servidores en Europa. Este sistema, basados en la experiencia, falla seguido, es tardado 
en contestar y a veces se cae por un tiempo considerable. Además, un ticket de soporte tarda varias semanas
en ser atendido. Este sistema no se puede cambiar y tenemos que trabajar con él porque nos da información importante.

== Detalles de Opeación

- Los clientes se pueden registrar solos, pero tienen que ser aprboardos por un administrador.
- Los pagos se pueden hacer con tarjeta de crédito o transferencia bancaria.
- Los clientes son personas importantes muy sensibles con su privacidad y seguridad.
- Hacer un vuelo es un compromiso fuerte, por lo que el sistema no puede decir que va a hacer un vuelo si no está seguro.
- No puede haber solicitudes o cancelaciones de vuelos en más de 6 meses y menos de 24 horas de anticipación.
- Las cancelaciones y situaciones extraordinarias se manejan por un administrador, fuera de la aplicación.

